baseURL = "https://zvlfahmi.github.io"
languageCode = "en-us"
DefaultContentLanguage = "en-us"
title = "ZulfahmiWeb"
paginate = 10
theme = "hulga"

[params]
  # show in HTML meta tag
  author = "Zulfahmi"
  keywords = "HTML, hugo, CSS"
  description = "Zulfahmi's blog"

  # change bulma's primary color
  primaryColor = "#1793d0"

  # subtitle on homepage
  subtitle = "Website Blog Asal Jadi"

  # copyright text on footer
  copyright = "made by zvlfahmi"

  # enable katex rendering on every post page
  math = true

  # enable postcss, mainly for css purge (129kB->20kB->4.8kB gzipped, but this makes build slower)
  postcss = false

  # enable toc on every post page
  toc = true

  # enable TOC auto collapse
  autoCollapseToc = true

  # enable prefers-color-scheme:dark
  darkMedia = true

  # enable hero section's is-bold effect
  heroBold = true

  # enable PWA, prepare your icons and DON'T forget to modify manifest.json
  pwa = true

  # disable jsdelivr cdn, default false
  noCDN = false

# to enable different hightlight themes in light/dark mode 
[markup]
  [markup.highlight]
    noClasses = false
[menu]
  [[menu.main]]
    identifier = "index"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "Archive"
    name = "Archive"
    url = "/yntkts/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

[taxonomies]
category = "categories"
tag = "tags"